### ISSUE TITLE
In witch json file i can find all data for every pokemon 

### ISSUE THREAD

**Issue by ViSurya** [kurayamiblackheart/kurayshinyrevamp#21]
Hey this is silly question

I am learning web development now I learning react so i wanna make my first pokeject so i want to make site like infinitefusiondex so can you just give me answer where can i find all data of pokemon

**Comment by kurayamiblackheart** [comment]
I assume you figured out, but if not, when you get debug in the game and go in the Debug menu, you can decompile the game (only on Kuray Infinite Fusion) using "Write Data" from that Debug Menu.

This decompile all the databases into easily readable .txt files inside a new folder called "PBS".
